# Generated by Django 3.2.16 on 2023-11-25 20:29

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.HexColorValidator()], verbose_name='HEX-цвет'),
        ),
    ]
