# Generated by Django 3.2.16 on 2023-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='Пароль'),
        ),
    ]
